sudo: required
services:
  - docker

before_install:
  - docker build -t alphakex2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alphakex2/react-test npm run test -- --coverage

after_success:
  - docker build -t alphakex2/multi-client ./client
  - docker build -t alphakex2/multi-nginx ./nginx
  - docker build -t alphakex2/multi-server ./server
  - docker build -t alphakex2/multi-worker ./worker
# Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push to docker
  - docker push alphakex2/multi-client
  - docker push alphakex2/multi-nginx
  - docker push alphakex2/multi-server
  - docker push alphakex2/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-462695455161
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"